### ISSUE TITLE
[v1.4.1] On browser, doesn't use the right protocol and port.

### ISSUE THREAD

**Issue by zallek** [BigstickCarpet/json-schema-ref-parser#11]
When using this lib served on localhost, the lib doesn't fetch json urls with the right **port** and **protocol**.

Some params aren't passed to `http` module which makes `http` lib resolve url to fetch according to current protocol and port.

Replacing this block at https://github.com/BigstickCarpet/json-schema-ref-parser/blob/v1.4.1/lib/read.js#L176
```JS
var req = protocol.get(
  {
    hostname: u.hostname,
    port: u.port,
    path: u.path,
    auth: u.auth
  },
  onResponse
);
```

by the following, solve the issue:
```JS
var req = protocol.get(
  {
    protocol: u.protocol,
    host: u.host,
    hostname: u.hostname,
    port: u.port,
    path: u.path,
    auth: u.auth
  },
  onResponse
);
```

**Comment by zallek** [comment]
I create a branch on my fork https://github.com/zallek/json-schema-ref-parser/tree/bugfix/port-and-protocol-resolving
commit: https://github.com/zallek/json-schema-ref-parser/commit/04d08b8a56636374556bed98edc80f4d9c04222e

But I can't create PR for your repo because I need a target branch based on v1.4.1 tag.

**Comment by BigstickCarpet** [comment]
This issue is fixed in newer versions of the library.  Please upgrade to the latest version, which includes many critical bug fixes, as well as many new features.
