### ISSUE TITLE
Add possibility to specify location when you pass object

### ISSUE THREAD

**Issue by IvanGoncharov** [BigstickCarpet/json-schema-ref-parser#13]
If you pass object it's impossible to resolve external relative references.
It would be cool if I can add option where I can specify base path for relative refs.

**Comment by BigstickCarpet** [comment]
I like this idea.  Will add it soon

**Comment by litek** [comment]
My current workaround is to just change working directory with `process.chdir` before resolving, then changing it back afterwards.

**Comment by alvassin** [comment]
+1. @BigstickCarpet Any progress on this?

**Comment by alvassin** [comment]
@litek workaround with changing working directory will not work if you deal with URLs (referenced issue).

**Comment by BigstickCarpet** [comment]
alright.  I'll get this knocked out this weekend

**Comment by BigstickCarpet** [comment]
As of version 3.1.1, you can now pass a URL _and_ an object to any method.

```javascript
$RefParser.dereference("http://example.com/my-schema.json", mySchemaObject, {})
```

> **NOTE:** As shown in the example above, you _must_ also pass an options object (even an empty object will work), otherwise, the method signature looks like you're just passing a URL and options.

**Comment by alvassin** [comment]
@BigstickCarpet thanks a lot for feature, but there is a bug: paths begin to duplicate (i pass `dereferenced.raml` file here, because schema is defined inside it and is relative to it):

```js
schema = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "items": {
      "$ref": "schemas/item.json"
    }
  }
}

deferred = @q.defer()
require('json-schema-ref-parser').dereference('test/raml-files/deferenced.raml', schema, {})
  .then((dereferencedSchema) ->
    deferred.resolve(JSON.stringify(dereferencedSchema))
  )
  .catch((err) ->
    deferred.reject(err)
  )
```

I'll get following error:
```
Error: Error resolving $ref pointer "test/raml-files/test/raml-files/schemas/item.json".
"test/raml-files/test/raml-files/schemas/item.json" not found.
```

**Comment by BigstickCarpet** [comment]
@alvassin - Good catch.  I had forgotten to account for relative URLs.  In all my tests, I was passing absolute URLs.  Anyway, it's fixed now.  Try the latest version

**Comment by alvassin** [comment]
@BigstickCarpet yeeeah! it works! thanks for super-fast fix, much appreciated 🍺
