### ISSUE TITLE
Invalid references created in `bundle` method

### ISSUE THREAD

**Issue by hielsnoppe** [BigstickCarpet/json-schema-ref-parser#15]
I am experiencing issues with the `bundle` method in a way that it creates broken references. See the following minimal example:

foo.json

    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "definitions": {
            "foodef": { "$ref": "bar.json#/definitions/bardef" }
        },
        "type": "object",
        "properties": {
            "prop": {
                "$ref": "#/definitions/foodef"
            }
        }
    }

bar.json

    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "definitions": {
            "bardef": { "type": "string" }
        }
    }

run.js

    var $RefParser = require('json-schema-ref-parser');

    $RefParser
        .bundle("foo.json")
        .then(function(schema) {
            console.log(JSON.stringify(schema, null, '    '));
        });

Running `node run.js > result.json` results in

result.json

    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "definitions": {
            "foodef": {
                "type": "string"
            }
        },
        "type": "object",
        "properties": {
            "prop": {
                "$ref": "#/definitions/foodef/definitions/bardef"
            }
        }
    }

There `#/definitions/foodef/definitions/bardef` is pointing nowhere.

Am I doing something wrong or is this a bug?

**Comment by BigstickCarpet** [comment]
I just released [version 3.0.0](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/CHANGELOG.md#v300-2016-04-03), which includes a fix for a very similar issue.  I think it may have fixed this issue as well.  Please give it a try and let me know.

I'm going to optimistically close this issue.  But feel free to re-open it if I've been too hasty. :)

**Comment by hielsnoppe** [comment]
Works for me. Thank you!
