### ISSUE TITLE
dereferencing ref of refs in the same path

### ISSUE THREAD

**Issue by educastellano** [BigstickCarpet/json-schema-ref-parser#21]
I'm trying to dereference some schemas, but seems that it does not resolve the urls the way I need... I'm probably missing some option here.

I have all the schemas sitting on /schemas:
`/schemas/a.json`
`/schemas/b.json`
`/schemas/c.json`

So `/schemas/a.json`:
```
{
    "b": { "$ref": "b.json" }
}
```
dereferences well, but `/schemas/b.json`:
```
{
    "c": { "$ref": "c.json" }
}
```
is trying to find the schema under `/schemas/b.json/`: 

- `GET http://localhost:8080/schemas/b.json/c.json/ 404 (Not Found)`
- `Error downloading http://localhost:8080/schemas/b.json/c.json/`

**Comment by BigstickCarpet** [comment]
That's odd.  Can you post a sample of how you're calling JSON Schema $Ref Parser?  I suspect that it may be something wrong with the parameters or usage.

**Comment by educastellano** [comment]
I'm just using it like this:

```
refParser.dereference('/schemas/a.json', (err, schema) => {
    if (err) {
        console.error(err)
    }
    else {
        console.log(schema)
    }
})
```

running in a web browser. I will do more testing tomorrow if you say it's supposed to work.

**Comment by BigstickCarpet** [comment]
Yeah, that should totally work.  I do essentially that same thing all the time.  And I have plenty of [tests](https://github.com/BigstickCarpet/json-schema-ref-parser/tree/master/test/specs) that cover that use-case as well.  There's gotta be some difference we're missing here.

Can you try using the un-minified version of JSON Schema $Ref Parser and then stepping into the code to see what's going on?

**Comment by educastellano** [comment]
I'm closing this since I had to move to something else. I was probably using it wrong...
