### ISSUE TITLE
Intermittent failures resolving filesystem $ref's

### ISSUE THREAD

**Issue by coltonlw** [BigstickCarpet/json-schema-ref-parser#26]
We have discovered that json-schema-ref-parser will intermittently fail resolving $ref's from the local filesystem.  The failure symptom is attempting to resolve the $ref relative to the current working directory, instead of the referring document.  This is estimated to happen about 1 of every 10 times.  

```
  1) PUT /users/{UserId} -> 200 "before all" hook: bound :
     Uncaught Error: Unable to expand schema:
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "../definitions/user.json#"
}
Error:
Error: Error opening file "/Users/coltonlw/projects/definitions/user.json"
ENOENT: no such file or directory, open '/Users/coltonlw/projects/definitions/user.json'
      at /usr/local/lib/node_modules/abao/lib/test.coffee:134:19
      at /usr/local/lib/node_modules/abao/node_modules/call-me-maybe/index.js:13:28
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

json-schema-ref-parser is attempting to load "/Users/coltonlw/projects/definitions/user.json", however the directory structure is like this:

/Users/coltonlw/projects/core/raml/schemas/definitions/user.json

With the referring document located at

/Users/coltonlw/projects/core/raml/schemas/output/user.json

**Comment by coltonlw** [comment]
To be clear this is using dereference() without using promises syntax, going to test promises now

**Comment by coltonlw** [comment]
After switching to promises syntax, I was able to run through 100 iterations of my test without a failure, so I'd say the issue is somewhere there.  Maybe related to call-me-maybe library.

**Comment by BigstickCarpet** [comment]
Odd.  It doesn't make sense that it would behave incorrectly only 10% of the time, and the code is the same regardless of whether it uses promises or callbacks.  I suspect that there's some other variable at play.  Perhaps you have multiple tests running simultaneously, and some of them are making modifications to the same folder structure that others are reading?

**Comment by coltonlw** [comment]
Nope, the folder structure isn't being modified.  As soon as we switched to promises the issue stopped happening, maybe callbacks aren't playing nice with whatever async setup our testing library (abao) is using.  I am new to nodejs so it's very possible I messed something up when I added json-schema-ref-parser to the abao testing library.  You can see where we call into json-schema-ref-parser here, and further up in that file you can also see how abao is implementing async behavior:

https://github.com/flywheel-io/abao/blob/add-jsonschema-deref/lib/test.coffee#L113

**Comment by coltonlw** [comment]
Here is what the code looked like when it had the issue, before switching to promises:   https://github.com/flywheel-io/abao/blob/015bf54a5b9a72b847e89a7a2b27f4a1c454f62d/lib/test.coffee#L113

**Comment by coltonlw** [comment]
This was due to my lack of knowledge in coffeescript syntax, closing
