### ISSUE TITLE
Fails to resolve multi-file #/definitions/ references

### ISSUE THREAD

**Issue by PrideDivide** [BigstickCarpet/json-schema-ref-parser#28]
I have my definitions in separate files, and the schemas in my paths link to them through the definitions object.

Swagger index file:
`
...
definitions:
  $ref: './definitions/index.yaml'
...
`

definitions/index.yaml:
`
...
  user:
    $ref: './main/user.yaml'
...
`

random path file:
`
...
get:
  responses:
    '200':
      schema:
        $ref: '#/definitions/user'
...
`

When I try to dereference this, I get the following error:

SyntaxError: Error resolving $ref pointer \"paths/main/user.yaml#/definitions/user\". ,
      "Token \"definitions\" does not exist.",

Is this supported? What am I doing wrong?

**Comment by BigstickCarpet** [comment]
That's the correct behavior.  JSON References (`$ref`) are resolved against the file _that they're in_, not against the root file.   See [this issue](https://github.com/BigstickCarpet/swagger-parser/issues/50) for more details

**Comment by PrideDivide** [comment]
Thanks for the quick response.
