### ISSUE TITLE
$refs files to definitions

### ISSUE THREAD

**Issue by cgarnier** [BigstickCarpet/json-schema-ref-parser#33]
Hello,
Is there a way to use this tool to replaces all $ref pointing to files by definitions ?

**Comment by BigstickCarpet** [comment]
Sounds like you're talking about [the `dereference()` method](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/docs/ref-parser.md#dereferenceschema-options-callback)

**Comment by cgarnier** [comment]
No, in fact i want to continue to use refs.
And replace the filesystem refs by embedded definitions.
I found an other way but it could be interesting to add this kind of feature.
