### ISSUE TITLE
Fails to deref https schemas, strips https off URL, ignores 301 redirect to https

### ISSUE THREAD

**Issue by n1ywb** [BigstickCarpet/json-schema-ref-parser#46]
![image](https://user-images.githubusercontent.com/316961/28881299-ac8f92d8-7775-11e7-9721-4cf9daa326d4.png)

url == `//json.readingpl.us/schemas/alertType.json`

url SHOULD equal `https://json.readingpl.us/schemas/alertType.json`

When redirected to HTTPS resource, it instead requests the HTTP resource again 

![image](https://user-images.githubusercontent.com/316961/28881414-0c9445b6-7776-11e7-9888-309f293512c1.png)

**Comment by n1ywb** [comment]
I noticed that this behavior does not occur when I serve my app with https.

**Comment by BigstickCarpet** [comment]
This error is caused by the URL resolution logic in the library.  It currently defaults to the protocol of the host page, rather than the protocol of the schema URL.

**Comment by rickyblaha** [comment]
+1

**Comment by rickyblaha** [comment]
I ended up writing my own resolver. Thanks for the awesome, easy to extend library :)

**Comment by big-r81** [comment]
Hi,

this is a real problem and you can run into CORS problems too, see #58.
If I debug and adding https in front of the url starting with "//...", the schema is fetched fine...

But I didn't find out, where the protocol is lost...
@BigstickCarpet Can you help?

**Comment by BigstickCarpet** [comment]
This issue was fixed by PR #59 and released in version 4.0.4

**Comment by big-r81** [comment]
@BigstickCarpet 

This issue is only partial fixed.

It won't follow the redirect for me. That still needs to be corrected!

**Comment by BigstickCarpet** [comment]
Oh...  I didn't even notice the redirect part of the issue.  I thought it was _just_ about the protocol bug.

Let's separate this into two different issues.  If the protocol bug is fixed, but the redirect bug is not, then can you create a new issue for _just_ the redirect bug?  That'll make things easier to track.
