### ISSUE TITLE
Some instructions are missing in Readme, Can't run karma tests

### ISSUE THREAD

**Issue by moejay** [BigstickCarpet/json-schema-ref-parser#50]
Hi,
I want to potentially use this library in an enterprise environment, and having a security flag ( even on a debug library ) is not a good thing from their point of view.

So I wanted to upgrade 'debug' to ^3.1.0, and I ran into some build issues from master.

Running on:
node v6.11.3
npm v3.10.10

Missing requirements from Readme:
`npm install -g karma mocha karma-cli`

When running `npm test`,  the karma step fails due to missing plugins.
I have had to modify karma.conf.js

I have made a build that fixes those issues, I can open a PR with the changes .
I can submit another PR for debug library version change.

Cheers,

**Comment by BigstickCarpet** [comment]
Hmmm... Mocha and Karma are both [listed in the devDependencies](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/package.json#L59-L69), so they should be installed as part of the `npm install` command.  My guess is that some errors occurred during the `npm install`, so not all dependencies were installed correctly.

**Comment by moejay** [comment]
They are, maybe it's a different version issue, but I had to add the
plugins to karma.conf.js, not package.json .
I will try a fresh checkout today again and confirm
Thanks

**Comment by moejay** [comment]
So I did some other tests, it turned out karma is running fine, but for some reason npm is exiting with error code 1 ( complaining about karma not working ) but you can see in the screenshot, the tests ran fine.
Not sure what exactly is happening :( 
<img width="1125" alt="screen shot 2017-10-08 at 10 32 38 am" src="https://user-images.githubusercontent.com/1688957/31317753-90fde50a-ac14-11e7-9283-bd0102a7b234.png">

Another maybe minor issue, is that what's in master is not the final .js ( But that can be fixed after any PR merge, just thought I would point it out )  , there are some differences once I run `npm test` 

<img width="607" alt="screen shot 2017-10-08 at 10 36 51 am" src="https://user-images.githubusercontent.com/1688957/31317764-a2cffa98-ac14-11e7-9e7c-bb455146fc27.png">

Anyway, If you don't have any ideas, I will close this issue, and I will open a new one for updating the debug library.

Cheers

**Comment by BigstickCarpet** [comment]
Ok, cool.  I'm glad you got the tests working.

The build step (which runs as part of `npm test`) inserts the current date into a comment at the top of the code, so it's normal for the `dist` files to appear to be modified.
