### ISSUE TITLE
Bundle/package directory

### ISSUE THREAD

**Issue by brettstack** [BigstickCarpet/json-schema-ref-parser#64]
The `bundle` method lets us pass in a file which then bundles all referenced files into a single schema and converts to local `$ref`s (though I'm encountering an issue with this which I think is the same as https://github.com/BigstickCarpet/json-schema-ref-parser/pull/62).

How difficult would it be to have something similar, but allow passing in a directory which merges all schemas and then converts to local `$ref`s?

I could merge all files into a single JSON quite easily; the challenging part would be converting the `$ref`s to their local equivalent.

**Comment by BigstickCarpet** [comment]
Hi @brettstack.  Couldn't you just create a file that references every file in the directory, and then pass that file to the `bundle()` method?
