### ISSUE TITLE
Regex in $ref path is URLEncoded

### ISSUE THREAD

**Issue by hipstersmoothie** [BigstickCarpet/json-schema-ref-parser#69]
When a schema has this structure:

```json
            "patternProperties": {
                "!(somePattern)": {
                    "$ref": "#/definitions/somethingElse"
                }
            }
```

When this is being bundled, the $ref to 'somethingElse' will be replaced with the schema object and all references to patternProperties/!(somePattern)/..../.../ will be invalid.

Is it possible to not store anything inside pattern properties? if no refs were ever stored here it would fix the bug.

**Comment by BigstickCarpet** [comment]
I'm not sure I understand the issue here.  It sounds like you're saying that you _don't_ want json-schema-ref-parser to dereference certain references in your schema.  Is that right?

**Comment by hipstersmoothie** [comment]
I don't remember anymore! closing
