### ISSUE TITLE
My schema (generated by Jackson from JAXB) has strange ids

### ISSUE THREAD

**Issue by vamsiampolu** [BigstickCarpet/json-schema-ref-parser#78]
My schema has ids that look like this:

```
"urn:jsonschema:com:mycompany:models:mali:Application"
```

that refer to elements within the same file. How can I specify to json-schema-ref-parser that these ids are local and that it should attempt to look up the id from a file?

**Comment by BigstickCarpet** [comment]
You can implement a [**custom resolver**](https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/docs/plugins/resolvers.md) for that
