### ISSUE TITLE
escaping json in $ref when converting spec to graphql schema

### ISSUE THREAD

**Issue by artivilla** [BigstickCarpet/json-schema-ref-parser#84]
One of the types in my swagger schema is as follows:
`$ref": "#/definitions/Get Item Subtypes by Type for Company"`

The error I'm getting is:
`Error: Definition Get%20Item%20Subtypes%20by%20Type%20for%20Company was not found in schema`

Is this not being excaped correctly? Is there a manual way to resove this?

**Comment by BigstickCarpet** [comment]
JSON References are URIs and should always be URI-encoded, [per the spec](https://tools.ietf.org/html/rfc6901#section-6).   However, if you don't URI-encode your references, then json-schema-ref-parser will try to automatically encode and decode them for you as needed.  **This is not bulletproof though**, so I suggest that you always URI-encode your references yourself.

I created a simple [**reproduction of your example**](https://runkit.com/bigstickcarpet/json-schema-ref-parser-issue-84) that demonstrates both a non-encoded reference and a properly-encoded reference.  In my example, json-schema-ref-parser was able to successfully handle even the non-encoded reference.  Not sure why it's not working in your case, but if you encode your references it should work

**Comment by artivilla** [comment]
Thank you for this @BigstickCarpet !
