### ISSUE TITLE
need it as a synchronous answer and not callback/promise

### ISSUE THREAD

**Issue by geetee24** [BigstickCarpet/json-schema-ref-parser#86]
Is this possible?

**Comment by BigstickCarpet** [comment]
You can use callbacks or promises, whichever you prefer.  See [the docs](https://github.com/BigstickCarpet/json-schema-ref-parser/tree/master/docs#callbacks-vs-promises) for more info

**Comment by geetee24** [comment]
are you aware of any other code library that does it synch?
